### ISSUE TITLE
Crash on Android 14 due to missing RECEIVER_EXPORTED / RECEIVER_NOT_EXPORTED flag

### ISSUE THREAD

**Issue by wba2hi** [bmwcarit/ramses-android#20]
Ramses Version: 
1.1.0

Android Device:
Google Pixel 8 Pro, Android 14 (API 34)

When calling RamsesThread#initRamsesThreadAndLoadScene the app crashes on Android 14 due to missing RECEIVER_EXPORTED / RECEIVER_NOT_EXPORTED flag during the registration of the RamshCommandBroadcastReceiver in RamsesBundle:24

The targetSdkVersion must be 34 for the crash to occur. 

See here for more information: https://developer.android.com/about/versions/14/behavior-changes-14#runtime-receivers-exported

```
java.lang.SecurityException: org.eclipse.kuksa.demo: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
at android.os.Parcel.createException(Parcel.java:3041)
at android.os.Parcel.readException(Parcel.java:3024)
at android.os.Parcel.readException(Parcel.java:2966)
at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5684)
at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1852)
at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
at android.app.ContextImpl.registerReceiver(ContextImpl.java:1780)
at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
at com.bmwgroup.ramses.RamsesBundle.<init>(RamsesBundle.java:49)
at com.bmwgroup.ramses.RamsesThread$1.run(RamsesThread.java:125)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: android.os.RemoteException: Remote stack trace:
at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:13927)
at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2570)
at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2720)
at android.os.Binder.execTransactInternal(Binder.java:1339)
at android.os.Binder.execTransact(Binder.java:1275)
```

**Comment by drindt** [comment]
# I solved this problem using a convention plugin. 

Please see the code for inspiration.
```kotlin
/*
 * Copyright (c) 2013-2024 The Coloryzer® Project
 *
 * All rights reserved. Unauthorized copying of this file, via any medium
 * is strictly prohibited Proprietary and confidential.
 *
 * Viselabs Inc.
 * Mahlsdorfer Straße 61b
 * 15366 Hoppegarten, Germany
 */

package coloryzer.ramses.receiver.fix

import org.objectweb.asm.Label
import org.objectweb.asm.MethodVisitor
import org.objectweb.asm.Opcodes

/**
 * This class is a visitor for modifying the constructor of the `com.bmwgroup.ramses.RamsesBundle` class
 * during bytecode manipulation using the ASM library.
 *
 * <p>
 * **Purpose:**
 * The primary goal is to adapt the broadcast receiver registration logic to handle Android API level differences,
 * specifically addressing the introduction of the `Context.RECEIVER_NOT_EXPORTED` flag in Android Tiramisu (API Level 33).
 * This ensures that the broadcast receiver is registered securely on newer Android versions
 * while maintaining compatibility with older versions.
 * </p>
 *
 * <p>
 * **Functionality:**
 * This transformer modifies the constructor of `RamsesBundle` to:
 * <ol>
 *     <li>Call the super constructor (Object).</li>
 *     <li>Initialize internal fields (`m_nativeObjectDisposed`, `m_sceneLoaded`, `m_nativeHandle`).</li>
 *     <li>Perform a null check on the provided Context and return early if null.</li>
 *     <li>Check the current Android API level using `Build.VERSION.SDK_INT`.</li>
 *     <li>Conditionally register the `RamshCommandBroadcastReceiver`:
 *         <ul>
 *             <li>For API Level 33 and above: Registers the receiver with the `RECEIVER_NOT_EXPORTED` flag for security.</li>
 *             <li>For API Level below 33: Uses the legacy registration method without the flag for compatibility.</li>
 *         </ul>
 *     </li>
 * </ol>
 * </p>
 *
 * <p>
 * **Bytecode Manipulation:**
 * ASM is used to inject the necessary bytecode instructions directly into the constructor method.
 * </p>
 */
class RamsesBundleConstructorTransformer(
    api: Int,
    methodVisitor: MethodVisitor,
) : MethodVisitor(api, methodVisitor) {
    override fun visitCode() {
        super.visitCode()

        /* Call the super constructor of RamsesBundle (java.lang.Object) */
        mv.visitVarInsn(Opcodes.ALOAD, ReceiverConstants.THIS_ARGUMENT_INDEX)
        mv.visitMethodInsn(
            Opcodes.INVOKESPECIAL,
            AndroidClassNames.OBJECT,
            MethodNames.CONSTRUCTOR,
            Descriptors.OBJECT_CONSTRUCTOR,
            false,
        )

        /* Initialize m_nativeObjectDisposed to false */
        mv.visitVarInsn(Opcodes.ALOAD, ReceiverConstants.THIS_ARGUMENT_INDEX)
        mv.visitInsn(Opcodes.ICONST_0)
        mv.visitFieldInsn(
            Opcodes.PUTFIELD,
            RamsesClassNames.RAMSES_BUNDLE,
            MethodNames.IS_NATIVE_OBJECT_DISPOSED,
            Descriptors.BOOLEAN,
        )

        /* Initialize m_sceneLoaded to false */
        mv.visitVarInsn(Opcodes.ALOAD, ReceiverConstants.THIS_ARGUMENT_INDEX)
        mv.visitInsn(Opcodes.ICONST_0)
        mv.visitFieldInsn(
            Opcodes.PUTFIELD,
            RamsesClassNames.RAMSES_BUNDLE,
            MethodNames.IS_SCENE_LOADED,
            Descriptors.BOOLEAN,
        )

        /* Initialize m_nativeHandle to this.createRamsesBundle() */
        mv.visitVarInsn(Opcodes.ALOAD, ReceiverConstants.THIS_ARGUMENT_INDEX)
        mv.visitVarInsn(Opcodes.ALOAD, ReceiverConstants.THIS_ARGUMENT_INDEX)
        mv.visitMethodInsn(
            Opcodes.INVOKESPECIAL,
            RamsesClassNames.RAMSES_BUNDLE,
            MethodNames.CREATE_RAMSES_BUNDLE,
            Descriptors.NATIVE_OBJECT_CONSTRUCTOR,
            false,
        )
        mv.visitFieldInsn(
            Opcodes.PUTFIELD,
            RamsesClassNames.RAMSES_BUNDLE,
            MethodNames.NATIVE_HANDLE,
            Descriptors.LONG,
        )

        /* Check for null */
        val notNull = Label()
        mv.visitVarInsn(Opcodes.ALOAD, ReceiverConstants.CONTEXT_ARGUMENT_INDEX)
        mv.visitJumpInsn(Opcodes.IFNONNULL, notNull)
        mv.visitInsn(Opcodes.RETURN)
        mv.visitLabel(notNull)

        /* Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU check in bytecode */
        mv.visitFieldInsn(
            Opcodes.GETSTATIC,
            AndroidClassNames.BUILD_VERSION,
            MethodNames.ANDROID_SDK_VERSION,
            Descriptors.INT,
        )

        /* TIRAMISU corresponds to API Level 33 */
        val legacyCodeLabel = Label()
        mv.visitIntInsn(Opcodes.BIPUSH, ReceiverConstants.TIRAMISU_API_LEVEL.level)

        /* Jump to legacyCode if SDK_INT < 33 */
        mv.visitJumpInsn(Opcodes.IF_ICMPLT, legacyCodeLabel)

        /* context.registerReceiver(..., ..., Context.RECEIVER_NOT_EXPORTED) for API Level 33+ */
        registerReceiver(mv, true)

        /* Jump to the end */
        val end = Label()
        mv.visitJumpInsn(Opcodes.GOTO, end)

        /* Legacy code for API Level < 33 */
        mv.visitLabel(legacyCodeLabel)
        registerReceiver(mv, false)

        /* End Label */
        mv.visitLabel(end)

        mv.visitInsn(Opcodes.RETURN)
        mv.visitEnd()
    }

    /**
     * Registers the RamshCommandBroadcastReceiver with the Android system.
     *
     * This method generates bytecode that:
     * 1. Creates a new instance of RamshCommandBroadcastReceiver.
     * 2. Gets the IntentFilter for Ramsh commands.
     * 3. Registers the receiver with the Context using the IntentFilter.
     *
     * If `useReceiverNotExported` is true, the receiver is registered with the
     * `RECEIVER_NOT_EXPORTED` flag, preventing other apps from sending broadcasts to it.
     * This is the recommended approach for security reasons.
     *
     * @param mv The MethodVisitor to write the bytecode to.
     * @param useReceiverNotExported Whether to register the receiver with the
     * `RECEIVER_NOT_EXPORTED` flag.
     */
    private fun registerReceiver(mv: MethodVisitor, useReceiverNotExported: Boolean) {
        mv.visitVarInsn(Opcodes.ALOAD, ReceiverConstants.CONTEXT_ARGUMENT_INDEX)
        mv.visitTypeInsn(
            Opcodes.NEW,
            RamsesClassNames.RAMSH_RECEIVER,
        )
        mv.visitInsn(Opcodes.DUP)
        mv.visitVarInsn(Opcodes.ALOAD, ReceiverConstants.THIS_ARGUMENT_INDEX)
        mv.visitMethodInsn(
            Opcodes.INVOKESPECIAL,
            RamsesClassNames.RAMSH_RECEIVER,
            MethodNames.CONSTRUCTOR,
            Descriptors.RECEIVER_CONSTRUCTOR,
            false,
        )
        mv.visitMethodInsn(
            Opcodes.INVOKESTATIC,
            RamsesClassNames.RAMSH_RECEIVER,
            MethodNames.GET_RAMSH_INTENT_FILTER,
            Descriptors.GET_RAMSH_COMMAND_INTENT_FILTER,
            false,
        )
        if (useReceiverNotExported) {
            mv.visitFieldInsn(
                Opcodes.GETSTATIC,
                AndroidClassNames.CONTEXT,
                ReceiverConstants.RECEIVER_NOT_EXPORTED_FLAG,
                ReceiverConstants.RECEIVER_NOT_EXPORTED_FLAG_TYPE,
            )
            mv.visitMethodInsn(
                Opcodes.INVOKEVIRTUAL,
                AndroidClassNames.CONTEXT,
                MethodNames.REGISTER_RECEIVER,
                Descriptors.REGISTER_RECEIVER_WITH_FLAGS,
                false,
            )
            mv.visitInsn(Opcodes.POP)
        } else {
            mv.visitMethodInsn(
                Opcodes.INVOKEVIRTUAL,
                AndroidClassNames.CONTEXT,
                MethodNames.REGISTER_RECEIVER,
                Descriptors.REGISTER_RECEIVER,
                false,
            )
            mv.visitInsn(Opcodes.POP)
        }
    }

    override fun visitMaxs(maxStack: Int, maxLocals: Int) {
        /**
         * Triggers automatic calculation of maxStack and maxLocals, which is crucial.
         * Do not call `mv.visitMaxs()` manually in visitCode() here.
         */
        super.visitMaxs(0, 0)
    }
}
```
